development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>   
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>