default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
 
development:
  <<: *default
  database: twitter_development
test:
  <<: *default
  database: twitter_test
production:
  <<: *default
  database: myapp_production
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>