# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63222660d3163dc15b8d233853b16bd74a6a79405d2f34aba76c8687b5f49bf9490fa72e3bb8c823b5a2f2df1fde53250ab9f05f8607943662d378aa5b89c416

test:
  secret_key_base: d5136fcaa4623e708942be3bdac177cf138959892d99ca5c97587ddbaa7b5d05332f03be76e1b8131177492c69b5ab7d7a4d3b4239f62891022e4a252b6170d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
